In [22]:
import tensorflow
import keras
import numpy as np
import pandas as pd

In [23]:
from tensorflow.keras.preprocessing.text import one_hot

In [24]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [25]:
### Vocabulary size
vocab_size=10000

In [26]:
# one hot representation
onehot_repr=[one_hot(words,vocab_size)for words in sent]
print(onehot_repr)

[[5557, 5986, 1026, 4256], [5557, 5986, 1026, 5777], [5557, 1177, 1026, 4090], [760, 5572, 118, 6739, 3123], [760, 5572, 118, 6739, 1308], [7436, 5557, 4922, 1026, 2571], [6811, 527, 3742, 6739]]


### Word Embedding Represntation

In [27]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [28]:
# Convert all sentences of same length
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5557 5986 1026 4256]
 [   0    0    0    0 5557 5986 1026 5777]
 [   0    0    0    0 5557 1177 1026 4090]
 [   0    0    0  760 5572  118 6739 3123]
 [   0    0    0  760 5572  118 6739 1308]
 [   0    0    0 7436 5557 4922 1026 2571]
 [   0    0    0    0 6811  527 3742 6739]]


In [29]:
# initialising dimensions
dim = 10

In [30]:
model = Sequential()
model.add(Embedding(vocab_size, 10, input_length = sent_length))
model.compile('adam', 'mse')

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [31]:
embedded_docs[0]

array([   0,    0,    0,    0, 5557, 5986, 1026, 4256], dtype=int32)

In [32]:
model.predict(embedded_docs)[0]

1/1 [==============================] - 0s 31ms/step


array([[-3.2236710e-02,  1.8474828e-02, -4.2285766e-02, -5.2176826e-03,
        -2.0518415e-03, -1.1708688e-02, -1.6939856e-02, -1.7025054e-02,
         1.2847770e-02, -1.4244638e-02],
       [-3.2236710e-02,  1.8474828e-02, -4.2285766e-02, -5.2176826e-03,
        -2.0518415e-03, -1.1708688e-02, -1.6939856e-02, -1.7025054e-02,
         1.2847770e-02, -1.4244638e-02],
       [-3.2236710e-02,  1.8474828e-02, -4.2285766e-02, -5.2176826e-03,
        -2.0518415e-03, -1.1708688e-02, -1.6939856e-02, -1.7025054e-02,
         1.2847770e-02, -1.4244638e-02],
       [-3.2236710e-02,  1.8474828e-02, -4.2285766e-02, -5.2176826e-03,
        -2.0518415e-03, -1.1708688e-02, -1.6939856e-02, -1.7025054e-02,
         1.2847770e-02, -1.4244638e-02],
       [-1.7153896e-02, -1.8650748e-02,  1.1895549e-02, -5.1580369e-05,
         3.8973812e-02,  5.7819001e-03, -4.7877338e-02,  3.5600517e-02,
         1.4265325e-02, -4.8650276e-02],
       [ 2.8851416e-02,  2.3542214e-02,  2.1579873e-02, -2.3341512e-02,
   